{"name": "Receiving a user's order without authorization", "status": "passed", "start": 1713953697781, "stop": 1713953697923, "uuid": "bc54d06a-6218-4672-a454-1f84e96a1506", "historyId": "4789c7aac39e50078c2e0c4aa7b44d12", "testCaseId": "4789c7aac39e50078c2e0c4aa7b44d12", "fullName": "tests.test_get_order.TestApiGetUserOrders#test_no_auth_user_get_user_order_error", "labels": [{"name": "feature", "value": "Checking receipt of the user's order"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestApiGetUserOrders"}, {"name": "host", "value": "IZY-PC"}, {"name": "thread", "value": "25448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}